- index.html
- styles/styles.css
> canvis css

- joc_virginia/index.php
> creación index.php

- joc_erfan/index.php
> push erfan demo

- joc_erfan/index.php
> prueba conflicto

- index.html
- styles/styles.css
> centrado del nav y +

- index.html
- styles/styles.css
> + cambios al html y css

- log_in.html
- styles/styles.css
> añadir log_in 21/10

- log_in.html
- styles/styles.css
> subir cambios log_in 21/10

- index.html
- jocs.html
> index y jocs

- log_in.html
> 90% en log-in

- log_in.html
> css log_in 21/10

- log_in.html
> log_in 22/10

- joc_virginia/index.php
> front juego_virginia

- joc_virginia/index.php
> front juego virginia

- joc_natalia/index.html
> laberinto añadido

- joc_erfan/index.html
- joc_erfan/scripts.js
Incorporacio de moviment de les gotes, setejar les gotes
> Avanç del joc

- joc_erfan/index.html
- joc_erfan/scripts.js
incoproar colisions i he intentat ficar les vides
> colisions / vides

- index.html
- joc_natalia/index.html
> cambios de hoy

- joc_virginia/joc_virginia.html
- joc_virginia/style.css
Separación del código en sus carpetas
> 02/11 ordenación

- joc_erfan/index.html
- joc_erfan/scripts.js
incorporades les vides dinamiques
> canvis joc erfan

- joc_virginia/joc_virginia.html
- joc_virginia/scripts.js
- joc_virginia/style.css
> añadir funciones

- joc_erfan/index.html
- joc_erfan/scripts.js
vides dinamiques solucionades amb data-
> vides solved

- joc_natalia/index.html
> cambios de hoy en el juego

- joc_natalia/index.html
ajustes de tamaño al laberinto
> ajustes de tamaño al laberinto

- joc_virginia/joc_virginia.html
- joc_virginia/scripts.js
- joc_virginia/style.css
- styles/styles.css
Añadir funcionalidades y recuento de puntos y vidas. Añadir función de finalización del juego.
> funcionalidades 05/11

- joc_virginia/joc_virginia.html
- joc_virginia/scripts.js
- joc_virginia/style.css
> style 05/11

- joc_virginia/scripts.js
> sin cambios

- joc_erfan/index.html
- joc_erfan/scripts.js
gotes incorporades a les gotes correctament, queda fraccionar el metode crear gota
> lletres incorporades

- joc_erfan/scripts.js
les gotes i les lletres s'esborren. També he incorporat que es llegexin les tecles del teclat i una clase al container gota que es igual que la lletra que es crea al span
> gotes i lletres

- joc_virginia/joc_virginia.html
- joc_virginia/scripts.js
- log_in.html
> función 06/11

- joc_erfan/scripts.js
> ultimo push

- joc_erfan/scripts.js
> Joc funcional

- joc_erfan/scripts.js
> joc proba 8/11

- joc_virginia/scripts.js
cambio variables para descuento de vidas en pez
> cambio variables 11/11

- joc_erfan/scripts.js
> una funcioneta

- joc_erfan/scripts.js
> comprovació

- log_in.php
- php_library/library.php
- registro.php
> session 26/11

- joc_virginia/joc_virginia.html
- joc_virginia/scripts.js
- joc_virginia/style.css
> final de juego

- joc_natalia/scripts.js
- joc_natalia/style.css
> changeeess

- joc_virginia/joc_virginia.html
> comentario

- joc_natalia/scripts.js
> cambioosss

- joc_natalia/scripts.js
> cambiosssssss

- joc_natalia/scripts.js
cambio en enviar_puntuacio de mi juego
> cambio en enviar_puntuacio de mi juego

- joc_natalia/scripts.js
> más cambios

- php_library/library.php
> conexio amb sql servidor

- .vscode/launch.json
- admin.php
- credits.html
- index.html
- joc_virginia/tutorial_virginia.html
- jocs.html
- log_in.html
- log_in.php
- ranquing.php
- registro.php
> push links

- ranquing.php
- styles/styles.css
> petitis canvis

- joc_roger/scripts.js
- joc_virginia/scripts.js
> canvis enivar punts

- joc_virginia/scripts.js
> canvis alba

- joc_erfan/scripts.js
- joc_jordi/piezas.js
- joc_virginia/scripts.js
- ranquing.php
- styles/styles.css
> ranking i direccions
